name: Perry de Loor Try out
favicon: null
layout_spectrum: 0.99984
typography_spectrum: 0.8212766
title: Site van Perry de Loor
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8bd8e2'
    - '#c5b168'
    - '#303e1a'
    - '#ac613f'
    - '#77221f'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0
purpose: []
