name: Perry de Loor Try out
favicon: null
layout_spectrum: 0.7543283984996378
typography_spectrum: 0.6233635547105223
title: Site van Perry de Loor
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  brandStrength: 0.244996641529724
  lightness: 0.4334656100254506
  saturation: 0.2866741456091404
  rhythmicContrast: 0.7229218201246113
purpose: []
