name: Perry de Loor Try out
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8212766
title: Site van Perry de Loor
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0f8857'
    - '#f6e9d1'
    - '#b09d6f'
    - '#c50029'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
