name: Perry de Loor Try out
favicon: null
layout_spectrum: 0.54654
typography_spectrum: 0.6446809
title: Site van Perry de Loor
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#383530'
    - '#989eaa'
    - '#fefefe'
    - '#897453'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
purpose: []
