name: Perrydltest
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aa5039'
    - '#28794c'
    - '#003d1a'
    - '#d4b16a'
    - '#ffe3aa'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
