name: Perrydltest
favicon: null
layout_spectrum: 0.65621
typography_spectrum: 0.58262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070709'
    - '#dacfbd'
    - '#786a5d'
    - '#b6ad9e'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
purpose: []
