name: Perrydltest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12110f'
    - '#675241'
    - '#5f7db3'
    - '#95aed7'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
