name: Perrydltest
favicon: null
layout_spectrum: 0.43064
typography_spectrum: 0.47767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aa5039'
    - '#aa8439'
    - '#7a296a'
    - '#551200'
    - '#ffbcaa'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
