layout_spectrum: 0.9361702
favicon: null
name: Perrydltest
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.793617
  lightness: 0.506383
  saturation: 0.4
  rhythmicContrast: 0.2829787
  brandColors:
    - '#aa5039'
    - '#28794c'
    - '#003d1a'
    - '#d4b16a'
    - '#ffe3aa'
typography_spectrum: 0.6446809
