typography_spectrum: 0.37563
color:
  brandColors:
    - '#000000'
    - '#0f8857'
    - '#f6e9d1'
    - '#b09d6f'
    - '#c50029'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Perry de Loor Try out
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: d23a653c-6f24-4b4b-9d7c-6f74cd708b53
    url: 2016-02-15-les-choses-en-face.html
    name: Les Choses en Face
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Site van Perry de Loor
purpose: []
